---
- name: Create new container and add current user public key
  hosts: crbio-host
  user: root
  tasks:

  - name: vzctl create
    shell: vzctl create {{ hostvars[container]['openvz-id'] }} --ostemplate {{ hostvars[container]['ostemplate'] }} --hostname {{ hostvars[container]['hostname'] }} --ipadd {{ hostvars[container]['host-ip'] }} 

  - name: set ram
    shell: vzctl set {{ hostvars[container]['openvz-id'] }} --ram {{ hostvars[container]['ram'] }} --save

  - name: set diskspace
    shell: vzctl set {{ hostvars[container]['openvz-id'] }} --diskspace {{ hostvars[container]['diskspace'] }} --save

  - name: start container
    shell: vzctl start {{ hostvars[container]['openvz-id'] }}
    tags:
      - configuration

  - name: make ssh directory
    file: path="{{ containers_fs_path }}/{{ hostvars[container]['openvz-id'] }}/root/.ssh" state=directory mode=700

  - name: copy ssh key
    copy: src="{{ lookup('env','HOME') }}/.ssh/id_rsa.pub" dest="{{ containers_fs_path }}/{{ hostvars[container]['openvz-id'] }}/root/.ssh/authorized_keys" mode=0600 
  #copy: src=
  #

  - name: apt-get update
    shell: vzctl exec {{ hostvars[container]['openvz-id'] }} apt-get update

  - name: install python-apt
    shell: vzctl exec {{ hostvars[container]['openvz-id'] }} apt-get -y install python-apt

